---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: external-dns@tidalwave-bootstrap.iam.gserviceaccount.com
  name: external-dns
  namespace: external-dns
