apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/MavenWave-DevOps/tidalwave-falco/falco
# - github.com/MavenWave-DevOps/tidalwave-falco/falco-ebpf-driver # Use for GKE
